// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orders.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	RzpId         string                 `protobuf:"bytes,3,opt,name=rzp_id,json=rzpId,proto3" json:"rzp_id,omitempty"`
	OrderItems    []*OrderItem           `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,6,opt,name=pincode,proto3" json:"pincode,omitempty"`
	CheckoutTotal float64                `protobuf:"fixed64,7,opt,name=checkout_total,json=checkoutTotal,proto3" json:"checkout_total,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	IsPaid        bool                   `protobuf:"varint,9,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	IsDelivered   bool                   `protobuf:"varint,10,opt,name=is_delivered,json=isDelivered,proto3" json:"is_delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDResponse) Reset() {
	*x = GetOrderByIDResponse{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDResponse) ProtoMessage() {}

func (x *GetOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderByIDResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetOrderByIDResponse) GetRzpId() string {
	if x != nil {
		return x.RzpId
	}
	return ""
}

func (x *GetOrderByIDResponse) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *GetOrderByIDResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetOrderByIDResponse) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *GetOrderByIDResponse) GetCheckoutTotal() float64 {
	if x != nil {
		return x.CheckoutTotal
	}
	return 0
}

func (x *GetOrderByIDResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetOrderByIDResponse) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *GetOrderByIDResponse) GetIsDelivered() bool {
	if x != nil {
		return x.IsDelivered
	}
	return false
}

type GetOrdersByCustomerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse       `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByCustomerIDResponse) Reset() {
	*x = GetOrdersByCustomerIDResponse{}
	mi := &file_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByCustomerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByCustomerIDResponse) ProtoMessage() {}

func (x *GetOrdersByCustomerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByCustomerIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByCustomerIDResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersByCustomerIDResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	RzpId         string                 `protobuf:"bytes,3,opt,name=rzp_id,json=rzpId,proto3" json:"rzp_id,omitempty"`
	OrderItems    []*OrderItem           `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,6,opt,name=pincode,proto3" json:"pincode,omitempty"`
	CheckoutTotal float64                `protobuf:"fixed64,7,opt,name=checkout_total,json=checkoutTotal,proto3" json:"checkout_total,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	IsPaid        bool                   `protobuf:"varint,9,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	IsDelivered   bool                   `protobuf:"varint,10,opt,name=is_delivered,json=isDelivered,proto3" json:"is_delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderResponse) GetRzpId() string {
	if x != nil {
		return x.RzpId
	}
	return ""
}

func (x *OrderResponse) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *OrderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderResponse) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *OrderResponse) GetCheckoutTotal() float64 {
	if x != nil {
		return x.CheckoutTotal
	}
	return 0
}

func (x *OrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderResponse) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *OrderResponse) GetIsDelivered() bool {
	if x != nil {
		return x.IsDelivered
	}
	return false
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{5}
}

func (x *GetKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSuccessRequest) Reset() {
	*x = PaymentSuccessRequest{}
	mi := &file_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessRequest) ProtoMessage() {}

func (x *PaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*PaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{6}
}

type PaymentSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSuccessResponse) Reset() {
	*x = PaymentSuccessResponse{}
	mi := &file_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessResponse) ProtoMessage() {}

func (x *PaymentSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessResponse.ProtoReflect.Descriptor instead.
func (*PaymentSuccessResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{7}
}

type PaymentFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailureRequest) Reset() {
	*x = PaymentFailureRequest{}
	mi := &file_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailureRequest) ProtoMessage() {}

func (x *PaymentFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailureRequest.ProtoReflect.Descriptor instead.
func (*PaymentFailureRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{8}
}

type PaymentFailureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailureResponse) Reset() {
	*x = PaymentFailureResponse{}
	mi := &file_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailureResponse) ProtoMessage() {}

func (x *PaymentFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailureResponse.ProtoReflect.Descriptor instead.
func (*PaymentFailureResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{9}
}

type PaymentCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackResponse) Reset() {
	*x = PaymentCallbackResponse{}
	mi := &file_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackResponse) ProtoMessage() {}

func (x *PaymentCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackResponse.ProtoReflect.Descriptor instead.
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{10}
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItems    []*OrderItem           `protobuf:"bytes,1,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orders_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{11}
}

func (x *CreateOrderRequest) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *CreateOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrderRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RzpId         string                 `protobuf:"bytes,2,opt,name=rzp_id,json=rzpId,proto3" json:"rzp_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OrderItems    []*OrderItem           `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,6,opt,name=pincode,proto3" json:"pincode,omitempty"`
	CheckoutTotal float64                `protobuf:"fixed64,7,opt,name=checkout_total,json=checkoutTotal,proto3" json:"checkout_total,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	IsPaid        bool                   `protobuf:"varint,9,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	IsDelivered   bool                   `protobuf:"varint,10,opt,name=is_delivered,json=isDelivered,proto3" json:"is_delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_orders_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse) GetRzpId() string {
	if x != nil {
		return x.RzpId
	}
	return ""
}

func (x *CreateOrderResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderResponse) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

func (x *CreateOrderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrderResponse) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateOrderResponse) GetCheckoutTotal() float64 {
	if x != nil {
		return x.CheckoutTotal
	}
	return 0
}

func (x *CreateOrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderResponse) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *CreateOrderResponse) GetIsDelivered() bool {
	if x != nil {
		return x.IsDelivered
	}
	return false
}

type UpdateDeliveryAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryAddressRequest) Reset() {
	*x = UpdateDeliveryAddressRequest{}
	mi := &file_orders_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryAddressRequest) ProtoMessage() {}

func (x *UpdateDeliveryAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryAddressRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDeliveryAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeliveryAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateDeliveryAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUpdated     bool                   `protobuf:"varint,1,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryAddressResponse) Reset() {
	*x = UpdateDeliveryAddressResponse{}
	mi := &file_orders_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryAddressResponse) ProtoMessage() {}

func (x *UpdateDeliveryAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryAddressResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDeliveryAddressResponse) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_orders_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{15}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCancelled   bool                   `protobuf:"varint,1,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_orders_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{16}
}

func (x *CancelOrderResponse) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x12\x06orders\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"%\n" +
	"\x13GetOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc5\x02\n" +
	"\x14GetOrderByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x15\n" +
	"\x06rzp_id\x18\x03 \x01(\tR\x05rzpId\x122\n" +
	"\vorder_items\x18\x04 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x06 \x01(\tR\apincode\x12%\n" +
	"\x0echeckout_total\x18\a \x01(\x01R\rcheckoutTotal\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_paid\x18\t \x01(\bR\x06isPaid\x12!\n" +
	"\fis_delivered\x18\n" +
	" \x01(\bR\visDelivered\"N\n" +
	"\x1dGetOrdersByCustomerIDResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.orders.OrderResponseR\x06orders\"\xbe\x02\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x15\n" +
	"\x06rzp_id\x18\x03 \x01(\tR\x05rzpId\x122\n" +
	"\vorder_items\x18\x04 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x06 \x01(\tR\apincode\x12%\n" +
	"\x0echeckout_total\x18\a \x01(\x01R\rcheckoutTotal\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_paid\x18\t \x01(\bR\x06isPaid\x12!\n" +
	"\fis_delivered\x18\n" +
	" \x01(\bR\visDelivered\"\"\n" +
	"\x0eGetKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x17\n" +
	"\x15PaymentSuccessRequest\"\x18\n" +
	"\x16PaymentSuccessResponse\"\x17\n" +
	"\x15PaymentFailureRequest\"\x18\n" +
	"\x16PaymentFailureResponse\"\x19\n" +
	"\x17PaymentCallbackResponse\"\x98\x01\n" +
	"\x12CreateOrderRequest\x122\n" +
	"\vorder_items\x18\x01 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xc4\x02\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06rzp_id\x18\x02 \x01(\tR\x05rzpId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x122\n" +
	"\vorder_items\x18\x04 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x06 \x01(\tR\apincode\x12%\n" +
	"\x0echeckout_total\x18\a \x01(\x01R\rcheckoutTotal\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_paid\x18\t \x01(\bR\x06isPaid\x12!\n" +
	"\fis_delivered\x18\n" +
	" \x01(\bR\visDelivered\"H\n" +
	"\x1cUpdateDeliveryAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\">\n" +
	"\x1dUpdateDeliveryAddressResponse\x12\x1d\n" +
	"\n" +
	"is_updated\x18\x01 \x01(\bR\tisUpdated\"$\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x13CancelOrderResponse\x12!\n" +
	"\fis_cancelled\x18\x01 \x01(\bR\visCancelled2\xcc\a\n" +
	"\rOrdersService\x12M\n" +
	"\x06GetKey\x12\x16.google.protobuf.Empty\x1a\x16.orders.GetKeyResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/orders/key\x12p\n" +
	"\x0ePaymentSuccess\x12\x1d.orders.PaymentSuccessRequest\x1a\x1e.orders.PaymentSuccessResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/orders/payment-success\x12p\n" +
	"\x0ePaymentFailure\x12\x1d.orders.PaymentFailureRequest\x1a\x1e.orders.PaymentFailureResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/orders/payment-failure\x12l\n" +
	"\x0fPaymentCallback\x12\x16.google.protobuf.Empty\x1a\x1f.orders.PaymentCallbackResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/orders/payment-callback\x12_\n" +
	"\fGetOrderByID\x12\x1b.orders.GetOrderByIDRequest\x1a\x1c.orders.GetOrderByIDResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/orders/{id}\x12~\n" +
	"\x15GetOrdersByCustomerID\x12\x16.google.protobuf.Empty\x1a%.orders.GetOrdersByCustomerIDResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/orders/customer/get-my-orders\x12Z\n" +
	"\vCreateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x1b.orders.CreateOrderResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/orders\x12\x7f\n" +
	"\x15UpdateDeliveryAddress\x12$.orders.UpdateDeliveryAddressRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/orders/{id}/delivery-address\x12\\\n" +
	"\vCancelOrder\x12\x1a.orders.CancelOrderRequest\x1a\x1b.orders.CancelOrderResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/orders/{id}B\aZ\x05../pbb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_orders_proto_goTypes = []any{
	(*OrderItem)(nil),                     // 0: orders.OrderItem
	(*GetOrderByIDRequest)(nil),           // 1: orders.GetOrderByIDRequest
	(*GetOrderByIDResponse)(nil),          // 2: orders.GetOrderByIDResponse
	(*GetOrdersByCustomerIDResponse)(nil), // 3: orders.GetOrdersByCustomerIDResponse
	(*OrderResponse)(nil),                 // 4: orders.OrderResponse
	(*GetKeyResponse)(nil),                // 5: orders.GetKeyResponse
	(*PaymentSuccessRequest)(nil),         // 6: orders.PaymentSuccessRequest
	(*PaymentSuccessResponse)(nil),        // 7: orders.PaymentSuccessResponse
	(*PaymentFailureRequest)(nil),         // 8: orders.PaymentFailureRequest
	(*PaymentFailureResponse)(nil),        // 9: orders.PaymentFailureResponse
	(*PaymentCallbackResponse)(nil),       // 10: orders.PaymentCallbackResponse
	(*CreateOrderRequest)(nil),            // 11: orders.CreateOrderRequest
	(*CreateOrderResponse)(nil),           // 12: orders.CreateOrderResponse
	(*UpdateDeliveryAddressRequest)(nil),  // 13: orders.UpdateDeliveryAddressRequest
	(*UpdateDeliveryAddressResponse)(nil), // 14: orders.UpdateDeliveryAddressResponse
	(*CancelOrderRequest)(nil),            // 15: orders.CancelOrderRequest
	(*CancelOrderResponse)(nil),           // 16: orders.CancelOrderResponse
	(*emptypb.Empty)(nil),                 // 17: google.protobuf.Empty
}
var file_orders_proto_depIdxs = []int32{
	0,  // 0: orders.GetOrderByIDResponse.order_items:type_name -> orders.OrderItem
	4,  // 1: orders.GetOrdersByCustomerIDResponse.orders:type_name -> orders.OrderResponse
	0,  // 2: orders.OrderResponse.order_items:type_name -> orders.OrderItem
	0,  // 3: orders.CreateOrderRequest.order_items:type_name -> orders.OrderItem
	0,  // 4: orders.CreateOrderResponse.order_items:type_name -> orders.OrderItem
	17, // 5: orders.OrdersService.GetKey:input_type -> google.protobuf.Empty
	6,  // 6: orders.OrdersService.PaymentSuccess:input_type -> orders.PaymentSuccessRequest
	8,  // 7: orders.OrdersService.PaymentFailure:input_type -> orders.PaymentFailureRequest
	17, // 8: orders.OrdersService.PaymentCallback:input_type -> google.protobuf.Empty
	1,  // 9: orders.OrdersService.GetOrderByID:input_type -> orders.GetOrderByIDRequest
	17, // 10: orders.OrdersService.GetOrdersByCustomerID:input_type -> google.protobuf.Empty
	11, // 11: orders.OrdersService.CreateOrder:input_type -> orders.CreateOrderRequest
	13, // 12: orders.OrdersService.UpdateDeliveryAddress:input_type -> orders.UpdateDeliveryAddressRequest
	15, // 13: orders.OrdersService.CancelOrder:input_type -> orders.CancelOrderRequest
	5,  // 14: orders.OrdersService.GetKey:output_type -> orders.GetKeyResponse
	7,  // 15: orders.OrdersService.PaymentSuccess:output_type -> orders.PaymentSuccessResponse
	9,  // 16: orders.OrdersService.PaymentFailure:output_type -> orders.PaymentFailureResponse
	10, // 17: orders.OrdersService.PaymentCallback:output_type -> orders.PaymentCallbackResponse
	2,  // 18: orders.OrdersService.GetOrderByID:output_type -> orders.GetOrderByIDResponse
	3,  // 19: orders.OrdersService.GetOrdersByCustomerID:output_type -> orders.GetOrdersByCustomerIDResponse
	12, // 20: orders.OrdersService.CreateOrder:output_type -> orders.CreateOrderResponse
	17, // 21: orders.OrdersService.UpdateDeliveryAddress:output_type -> google.protobuf.Empty
	16, // 22: orders.OrdersService.CancelOrder:output_type -> orders.CancelOrderResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
