// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: products.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Rating        uint64                 `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Reviews       uint64                 `protobuf:"varint,9,opt,name=reviews,proto3" json:"reviews,omitempty"`
	Stock         uint64                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,11,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetReviews() uint64 {
	if x != nil {
		return x.Reviews
	}
	return 0
}

func (x *Product) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Rating        uint64                 `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Reviews       uint64                 `protobuf:"varint,9,opt,name=reviews,proto3" json:"reviews,omitempty"`
	Stock         uint64                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,11,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDResponse) Reset() {
	*x = GetProductByIDResponse{}
	mi := &file_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDResponse) ProtoMessage() {}

func (x *GetProductByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductByIDResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductByIDResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductByIDResponse) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *GetProductByIDResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductByIDResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetProductByIDResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetProductByIDResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductByIDResponse) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetProductByIDResponse) GetReviews() uint64 {
	if x != nil {
		return x.Reviews
	}
	return 0
}

func (x *GetProductByIDResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetProductByIDResponse) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *GetProductByIDResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetProductsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []uint64               `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsRequest) Reset() {
	*x = GetProductsByIDsRequest{}
	mi := &file_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsRequest) ProtoMessage() {}

func (x *GetProductsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsByIDsRequest) GetProductIds() []uint64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetProductsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsResponse) Reset() {
	*x = GetProductsByIDsResponse{}
	mi := &file_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsResponse) ProtoMessage() {}

func (x *GetProductsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsByIDsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Rating        uint64                 `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Reviews       uint64                 `protobuf:"varint,9,opt,name=reviews,proto3" json:"reviews,omitempty"`
	Stock         uint64                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,11,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{5}
}

func (x *ProductResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductResponse) GetReviews() uint64 {
	if x != nil {
		return x.Reviews
	}
	return 0
}

func (x *ProductResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ProductResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,2,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Stock         uint64                 `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,7,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{6}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *AddProductRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductRequest) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *AddProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Rating        uint64                 `protobuf:"varint,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Reviews       uint64                 `protobuf:"varint,9,opt,name=reviews,proto3" json:"reviews,omitempty"`
	Stock         uint64                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,11,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{7}
}

func (x *AddProductResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductResponse) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *AddProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductResponse) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddProductResponse) GetReviews() uint64 {
	if x != nil {
		return x.Reviews
	}
	return 0
}

func (x *AddProductResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductResponse) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *AddProductResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CalculateTotalPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItems    []*OrderItem           `protobuf:"bytes,1,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateTotalPriceRequest) Reset() {
	*x = CalculateTotalPriceRequest{}
	mi := &file_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTotalPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTotalPriceRequest) ProtoMessage() {}

func (x *CalculateTotalPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTotalPriceRequest.ProtoReflect.Descriptor instead.
func (*CalculateTotalPriceRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateTotalPriceRequest) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type CalculateTotalPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPrice    float64                `protobuf:"fixed64,1,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateTotalPriceResponse) Reset() {
	*x = CalculateTotalPriceResponse{}
	mi := &file_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTotalPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTotalPriceResponse) ProtoMessage() {}

func (x *CalculateTotalPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTotalPriceResponse.ProtoReflect.Descriptor instead.
func (*CalculateTotalPriceResponse) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{9}
}

func (x *CalculateTotalPriceResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalPrice float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Stock         uint64                 `protobuf:"varint,10,opt,name=stock,proto3" json:"stock,omitempty"`
	InStock       bool                   `protobuf:"varint,11,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *UpdateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_products_proto protoreflect.FileDescriptor

const file_products_proto_rawDesc = "" +
	"\n" +
	"\x0eproducts.proto\x12\bproducts\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\forders.proto\"\xe6\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\b \x01(\x04R\x06rating\x12\x18\n" +
	"\areviews\x18\t \x01(\x04R\areviews\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\v \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xc4\x02\n" +
	"\x16GetProductByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\b \x01(\x04R\x06rating\x12\x18\n" +
	"\areviews\x18\t \x01(\x04R\areviews\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\v \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\":\n" +
	"\x17GetProductsByIDsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x04R\n" +
	"productIds\"Q\n" +
	"\x18GetProductsByIDsResponse\x125\n" +
	"\bproducts\x18\x01 \x03(\v2\x19.products.ProductResponseR\bproducts\"\xbd\x02\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\b \x01(\x04R\x06rating\x12\x18\n" +
	"\areviews\x18\t \x01(\x04R\areviews\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\v \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\"\xe7\x01\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x02 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\a \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\xc0\x02\n" +
	"\x12AddProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\b \x01(\x04R\x06rating\x12\x18\n" +
	"\areviews\x18\t \x01(\x04R\areviews\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\v \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\"P\n" +
	"\x1aCalculateTotalPriceRequest\x122\n" +
	"\vorder_items\x18\x01 \x03(\v2\x11.orders.OrderItemR\n" +
	"orderItems\">\n" +
	"\x1bCalculateTotalPriceResponse\x12\x1f\n" +
	"\vtotal_price\x18\x01 \x01(\x01R\n" +
	"totalPrice\"\x90\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x14\n" +
	"\x05stock\x18\n" +
	" \x01(\x04R\x05stock\x12\x19\n" +
	"\bin_stock\x18\v \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\xa1\x05\n" +
	"\x0fProductsService\x12k\n" +
	"\x0eGetProductByID\x12\x1f.products.GetProductByIDRequest\x1a .products.GetProductByIDResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/products/{id}\x12l\n" +
	"\x10GetProductsByIDs\x12!.products.GetProductsByIDsRequest\x1a\".products.GetProductsByIDsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/products\x12]\n" +
	"\n" +
	"AddProduct\x12\x1b.products.AddProductRequest\x1a\x1c.products.AddProductResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/products\x12\x8e\x01\n" +
	"\x13CalculateTotalPrice\x12$.products.CalculateTotalPriceRequest\x1a%.products.CalculateTotalPriceResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/products/calculate-total-price\x12b\n" +
	"\rUpdateProduct\x12\x1e.products.UpdateProductRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/products/{id}\x12_\n" +
	"\rDeleteProduct\x12\x1e.products.DeleteProductRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/products/{id}B\aZ\x05../pbb\x06proto3"

var (
	file_products_proto_rawDescOnce sync.Once
	file_products_proto_rawDescData []byte
)

func file_products_proto_rawDescGZIP() []byte {
	file_products_proto_rawDescOnce.Do(func() {
		file_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)))
	})
	return file_products_proto_rawDescData
}

var file_products_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_products_proto_goTypes = []any{
	(*Product)(nil),                     // 0: products.Product
	(*GetProductByIDRequest)(nil),       // 1: products.GetProductByIDRequest
	(*GetProductByIDResponse)(nil),      // 2: products.GetProductByIDResponse
	(*GetProductsByIDsRequest)(nil),     // 3: products.GetProductsByIDsRequest
	(*GetProductsByIDsResponse)(nil),    // 4: products.GetProductsByIDsResponse
	(*ProductResponse)(nil),             // 5: products.ProductResponse
	(*AddProductRequest)(nil),           // 6: products.AddProductRequest
	(*AddProductResponse)(nil),          // 7: products.AddProductResponse
	(*CalculateTotalPriceRequest)(nil),  // 8: products.CalculateTotalPriceRequest
	(*CalculateTotalPriceResponse)(nil), // 9: products.CalculateTotalPriceResponse
	(*UpdateProductRequest)(nil),        // 10: products.UpdateProductRequest
	(*DeleteProductRequest)(nil),        // 11: products.DeleteProductRequest
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
	(*OrderItem)(nil),                   // 13: orders.OrderItem
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_products_proto_depIdxs = []int32{
	12, // 0: products.Product.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: products.Product.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: products.Product.deleted_at:type_name -> google.protobuf.Timestamp
	5,  // 3: products.GetProductsByIDsResponse.products:type_name -> products.ProductResponse
	13, // 4: products.CalculateTotalPriceRequest.order_items:type_name -> orders.OrderItem
	1,  // 5: products.ProductsService.GetProductByID:input_type -> products.GetProductByIDRequest
	3,  // 6: products.ProductsService.GetProductsByIDs:input_type -> products.GetProductsByIDsRequest
	6,  // 7: products.ProductsService.AddProduct:input_type -> products.AddProductRequest
	8,  // 8: products.ProductsService.CalculateTotalPrice:input_type -> products.CalculateTotalPriceRequest
	10, // 9: products.ProductsService.UpdateProduct:input_type -> products.UpdateProductRequest
	11, // 10: products.ProductsService.DeleteProduct:input_type -> products.DeleteProductRequest
	2,  // 11: products.ProductsService.GetProductByID:output_type -> products.GetProductByIDResponse
	4,  // 12: products.ProductsService.GetProductsByIDs:output_type -> products.GetProductsByIDsResponse
	7,  // 13: products.ProductsService.AddProduct:output_type -> products.AddProductResponse
	9,  // 14: products.ProductsService.CalculateTotalPrice:output_type -> products.CalculateTotalPriceResponse
	14, // 15: products.ProductsService.UpdateProduct:output_type -> google.protobuf.Empty
	14, // 16: products.ProductsService.DeleteProduct:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_products_proto_init() }
func file_products_proto_init() {
	if File_products_proto != nil {
		return
	}
	file_orders_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_proto_goTypes,
		DependencyIndexes: file_products_proto_depIdxs,
		MessageInfos:      file_products_proto_msgTypes,
	}.Build()
	File_products_proto = out.File
	file_products_proto_goTypes = nil
	file_products_proto_depIdxs = nil
}
